name: Cabal build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: haskell/actions/setup@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
    - run: cabal build
    - run: cabal test
